"""ND2 -> OME-Zarr pyramid conversion.

Writes an OME-NGFF 0.4 multiscales group (zarr v2 layout for maximum viewer
compatibility: napari, vizarr, ome-zarr-py, QuPath all read it today):

    out.zarr/
      .zattrs          multiscales + omero + nd2wsi metadata
      .zgroup
      0/               level 0, shape (C, Y, X), chunks (1, tile, tile)
      1/               level 1 = level 0 downsampled 2x (2x2 mean)
      ...

Every step is memory-bounded:

* level 0 streams straight out of the ND2 memory map in (1, tile, tile)
  chunks (see :mod:`nd2wsi.reader`);
* level k+1 is computed from the *zarr* level k with a chunk-aligned
  2x2 mean (dask ``coarsen``), so nothing larger than a few tiles is ever
  resident.
"""

from __future__ import annotations

import json
import math
import shutil
import time
from pathlib import Path
from typing import Any

import numpy as np

from .reader import PlaneSelection, PlaneSource, level_shapes, nice_bytes, open_plane

NGFF_VERSION = "0.4"


def _create_level_array(
    root: Any, path: str, shape: tuple[int, ...], dtype: np.dtype, tile: int
) -> Any:
    import zarr
    from numcodecs import Blosc

    return root.create_array(
        name=path,
        shape=shape,
        chunks=(1, tile, tile),
        dtype=dtype,
        compressors=Blosc(cname="zstd", clevel=3, shuffle=Blosc.BITSHUFFLE),
        dimension_names=None,
        overwrite=True,
    )


def _even_chunks(size: int, chunk: int) -> tuple[int, ...]:
    """Chunk layout for `size` where every chunk is even-length (last may differ).

    Used before 2x2 coarsening: `size` must already be even; `chunk` is even.
    """
    if size <= 0:
        return (0,)
    n_full, rem = divmod(size, chunk)
    chunks = [chunk] * n_full
    if rem:
        chunks.append(rem)
    return tuple(chunks)


def _write_level0(src: PlaneSource, arr: Any) -> None:
    import dask.array as da

    da.store(src.data, arr, lock=False)


def _downsample_into(prev_arr: Any, next_arr: Any, tile: int, dtype: np.dtype) -> None:
    import dask.array as da

    c, ph, pw = prev_arr.shape
    _, nh, nw = next_arr.shape
    eh, ew = nh * 2, nw * 2  # even source extent actually consumed

    prev = da.from_zarr(prev_arr)[:, :eh, :ew]
    prev = prev.rechunk((1, _even_chunks(eh, 2 * tile), _even_chunks(ew, 2 * tile)))
    mean = da.coarsen(np.mean, prev, {1: 2, 2: 2})
    if np.issubdtype(dtype, np.integer):
        mean = da.rint(mean)
    da.store(mean.astype(dtype), next_arr, lock=False)


def _percentile_windows(
    root: Any, level_paths: list[str], src: PlaneSource
) -> list[dict[str, float]]:
    """Per-channel display windows from the smallest pyramid level."""
    small = np.asarray(root[level_paths[-1]][:])
    info = np.iinfo(src.dtype) if np.issubdtype(src.dtype, np.integer) else None
    lo_all = float(info.min) if info else float(np.nanmin(small))
    hi_all = float(info.max) if info else float(np.nanmax(small))
    windows = []
    for ci in range(small.shape[0]):
        ch = small[ci]
        if src.rgb:
            start, end = 0.0, 255.0
        else:
            start = float(np.percentile(ch, 1.0))
            end = float(np.percentile(ch, 99.8))
            if end <= start:
                end = start + 1.0
        windows.append({"start": start, "end": end, "min": lo_all, "max": hi_all})
    return windows


def _hex_color(rgb: tuple[int, int, int]) -> str:
    return "%02X%02X%02X" % rgb


def build_group_attrs(
    src: PlaneSource,
    shapes: list[tuple[int, int]],
    tile: int,
    windows: list[dict[str, float]],
) -> dict[str, Any]:
    py, px = src.pixel_size_um
    datasets = []
    for k, (h, w) in enumerate(shapes):
        factor = 2**k
        datasets.append(
            {
                "path": str(k),
                "coordinateTransformations": [
                    {"type": "scale", "scale": [1.0, py * factor, px * factor]}
                ],
            }
        )
    multiscales = [
        {
            "version": NGFF_VERSION,
            "name": Path(src.source_name).name,
            "axes": [
                {"name": "c", "type": "channel"},
                {"name": "y", "type": "space", "unit": "micrometer"},
                {"name": "x", "type": "space", "unit": "micrometer"},
            ],
            "datasets": datasets,
            "type": "2x2 local mean",
            "metadata": {"description": "generated by nd2wsi"},
        }
    ]
    omero = {
        "channels": [
            {
                "label": ch.name,
                "color": _hex_color(ch.color),
                "active": True,
                "window": windows[i],
            }
            for i, ch in enumerate(src.channels)
        ],
        "rdefs": {"model": "color"},
    }
    levels = [
        {"path": str(k), "width": w, "height": h, "downsample": 2**k}
        for k, (h, w) in enumerate(shapes)
    ]
    nd2wsi = {
        "rgb": src.rgb,
        "source": Path(src.source_name).name,
        "pixel_size_um": [py, px],
        "dtype": str(src.dtype),
        "tile": tile,
        "levels": levels,
        "selection": src.selection,
        "notes": src.notes,
        "objective_magnification": src.magnification,
    }
    return {"multiscales": multiscales, "omero": omero, "nd2wsi": nd2wsi}


def convert(
    nd2_path: str | Path,
    out_path: str | Path,
    *,
    tile: int = 512,
    selection: PlaneSelection | None = None,
    overwrite: bool = False,
    progress: bool = True,
    workers: int = 4,
) -> Path:
    """Convert one plane of an ND2 file to an OME-Zarr pyramid on disk."""
    import dask
    import nd2
    import zarr

    nd2_path = Path(nd2_path)
    out_path = Path(out_path)
    selection = selection or PlaneSelection()

    if out_path.exists():
        if not overwrite:
            raise FileExistsError(f"{out_path} exists (use --overwrite)")
        shutil.rmtree(out_path)

    t0 = time.time()
    with dask.config.set(scheduler="threads", num_workers=workers):
        with nd2.ND2File(str(nd2_path)) as f:
            src = open_plane(f, selection, tile=tile)
            c, h, w = src.shape
            shapes = level_shapes(h, w, tile)
            if progress:
                raw = c * h * w * src.dtype.itemsize
                print(
                    f"{nd2_path.name}: {w} x {h} px, {c} channel(s), "
                    f"{src.dtype}, {'RGB' if src.rgb else 'grayscale'}, "
                    f"~{nice_bytes(raw)} of level-0 pixels"
                )
                for note in src.notes:
                    print(f"  note: {note}")
                print(f"  pyramid: {len(shapes)} levels, tile {tile}")

            root = zarr.open_group(str(out_path), mode="w", zarr_format=2)
            arrays = []
            for k, (lh, lw) in enumerate(shapes):
                arrays.append(
                    _create_level_array(root, str(k), (c, lh, lw), src.dtype, tile)
                )

            if progress:
                print(f"  level 0  {w} x {h}  writing from ND2 ...", flush=True)
            _write_level0(src, arrays[0])

            for k in range(1, len(shapes)):
                lh, lw = shapes[k]
                if progress:
                    print(f"  level {k}  {lw} x {lh}  downsampling ...", flush=True)
                _downsample_into(arrays[k - 1], arrays[k], tile, src.dtype)

            windows = _percentile_windows(root, [str(k) for k in range(len(shapes))], src)
            root.attrs.update(build_group_attrs(src, shapes, tile, windows))

    if progress:
        size = sum(p.stat().st_size for p in out_path.rglob("*") if p.is_file())
        print(
            f"  done in {time.time() - t0:.1f}s -> {out_path} ({nice_bytes(size)} on disk)"
        )
    return out_path


def default_store_path(nd2_path: str | Path, cache_dir: str | Path | None = None) -> Path:
    nd2_path = Path(nd2_path)
    base = Path(cache_dir) if cache_dir else nd2_path.parent
    return base / (nd2_path.stem + ".ome.zarr")


def open_store(path: str | Path) -> tuple[Any, dict[str, Any]]:
    """Open a converted store, returning (zarr group, attrs dict)."""
    import zarr

    root = zarr.open_group(str(path), mode="r")
    attrs = json.loads(json.dumps(dict(root.attrs)))
    if "nd2wsi" not in attrs or "multiscales" not in attrs:
        raise ValueError(
            f"{path} does not look like an nd2wsi store "
            "(missing multiscales/nd2wsi metadata)"
        )
    return root, attrs


def mpx(w: int, h: int) -> float:
    return w * h / 1e6


def ceil_log2(n: int) -> int:
    return int(math.ceil(math.log2(max(1, n))))
