#!/usr/bin/env python3
"""Build and smoke-test the portable Windows x64 executable.

Run with the locked Windows environment; see .github/workflows/windows.yml.
An x64 build also runs under Windows 11 ARM64's built-in x64 emulation.
This script deliberately has no option to skip the packaged release checks.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import os
import platform
import re
import shutil
import struct
import subprocess
import sys
import tomllib
import zipfile
from pathlib import Path, PurePosixPath

REPO = Path(__file__).resolve().parents[1]
APP = "nd2wsi-viewer"


def run(*args: str | Path) -> None:
    subprocess.run([str(arg) for arg in args], cwd=REPO, check=True)


def sha256(path: Path) -> str:
    with path.open("rb") as source:
        return hashlib.file_digest(source, "sha256").hexdigest()


def verify_source_files(provenance: dict) -> None:
    """Require the exact source bytes named by a local snapshot manifest."""
    files = provenance.get("files")
    if not isinstance(files, dict) or not files:
        raise ValueError("Source manifest must contain a nonempty files SHA-256 mapping")
    for relative, expected in files.items():
        path = PurePosixPath(relative)
        if (path.is_absolute() or ".." in path.parts or "\\" in relative
                or ":" in relative or str(path) != relative):
            raise ValueError(f"Invalid relative source path: {relative}")
        if not isinstance(expected, str) or not re.fullmatch(r"[0-9a-f]{64}", expected):
            raise ValueError(f"Invalid source SHA-256: {relative}")
        actual = REPO / relative
        if not actual.is_file() or sha256(actual) != expected:
            raise ValueError(f"Source snapshot checksum mismatch: {relative}")
    required = {
        "pyproject.toml", "uv.lock", "LICENSE", "packaging/build_windows.py",
        "packaging/launch.py", "packaging/AppIcon.icns", "packaging/WINDOWS-README.txt",
        "packaging/windows-build-requirements.txt",
    }
    # Generated bytecode can be created by imports/tests. Every actual module
    # and static resource shipped by collect-all must belong to the snapshot.
    required.update(str(path.relative_to(REPO).as_posix())
                    for path in (REPO / "nd2wsi").rglob("*")
                    if path.is_file() and "__pycache__" not in path.parts
                    and path.suffix != ".pyc")
    missing = required - set(files)
    if missing:
        raise ValueError(f"Source manifest omits build inputs: {sorted(missing)}")


def source_provenance(source_manifest: Path | None) -> dict:
    if source_manifest is not None:
        result = json.loads(source_manifest.read_text(encoding="utf-8-sig"))
        if result.get("schema_version") != 1:
            raise ValueError("Unsupported source manifest schema_version")
        if not re.fullmatch(r"[0-9a-f]{40}", result.get("base_commit", "")):
            raise ValueError("Source manifest requires the full base Git commit SHA")
        if type(result.get("working_tree_dirty")) is not bool:
            raise ValueError("Source manifest requires a boolean working_tree_dirty")
        result["source_kind"] = "local-working-tree-snapshot"
        result["manifest_sha256"] = sha256(source_manifest)
    else:
        # Git is only needed for a checkout build, never in a snapshot guest.
        try:
            commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO, text=True).strip()
            status = subprocess.check_output(["git", "status", "--porcelain"], cwd=REPO)
            names = subprocess.check_output(
                ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"], cwd=REPO
            ).decode("utf-8").split("\0")
        except (OSError, subprocess.CalledProcessError) as exc:
            raise RuntimeError("No Git checkout available; pass --source-manifest SOURCE-MANIFEST.json") from exc
        result = {
            "schema_version": 1,
            "source_kind": "git-working-tree",
            "base_commit": commit,
            "working_tree_dirty": bool(status.strip()),
            "files": {name: sha256(REPO / name) for name in sorted(set(names))
                      if name and (REPO / name).is_file()},
        }
    verify_source_files(result)
    content = json.dumps(result["files"], sort_keys=True, separators=(",", ":")).encode("utf-8")
    result["snapshot_sha256"] = hashlib.sha256(content).hexdigest()
    return result


def smoke(exe: Path, source: Path, evidence: Path) -> None:
    """Exercise the actual windowed EXE, including the WebView2 renderer."""
    evidence.mkdir(parents=True, exist_ok=True)
    for flag, limit in (("--smoke", 600), ("--gui-smoke", 180)):
        name = flag.removeprefix("--")
        log = evidence / f"{name}.log"
        log.unlink(missing_ok=True)
        env = dict(os.environ, ND2WSI_LOG_FILE=str(log))
        command = [str(exe), flag, str(source)]
        report = evidence / "gui-smoke.json"
        if flag == "--gui-smoke":
            report.unlink(missing_ok=True)
            command += ["--smoke-report", str(report)]
        result = subprocess.run(command, env=env, timeout=limit)
        if log.exists():
            print(log.read_text(encoding="utf-8", errors="replace"))
        if result.returncode:
            raise RuntimeError(f"Packaged {flag} failed with exit {result.returncode}")
        if flag == "--gui-smoke":
            if not report.exists() or json.loads(report.read_text(encoding="utf-8")).get("ok") is not True:
                raise RuntimeError("Packaged GUI smoke did not record successful completion")
        elif not log.exists() or "smoke ok" not in log.read_text(encoding="utf-8"):
            raise RuntimeError(f"Packaged {flag} did not record successful completion")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--smoke-file", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=REPO / "dist" / "windows")
    parser.add_argument("--source-manifest", type=Path,
                        help="exact source snapshot manifest; avoids requiring Git on the build machine")
    args = parser.parse_args()
    if sys.platform != "win32" or struct.calcsize("P") != 8:
        parser.error("Build on Windows with 64-bit x64 CPython, not by cross-compiling")
    # platform.machine() reports the host under some emulators; the compiler
    # describes the interpreter architecture that determines the frozen binary.
    if "AMD64" not in platform.python_compiler().upper():
        parser.error("Use the x64 CPython interpreter; this package is not native ARM64")
    source = args.smoke_file.resolve(strict=True)
    provenance = source_provenance(args.source_manifest)
    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=True)
    build = REPO / "build" / "windows"
    build.mkdir(parents=True, exist_ok=True)
    version = tomllib.loads((REPO / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]

    # Fail before packaging if either scientific export or image codecs is absent.
    run(sys.executable, "-c", "import _tkinter, limnd2, imagecodecs, clr, webview; "
        "assert imagecodecs.JPEG.available and imagecodecs.JPEG2K.available")
    from PIL import Image

    icon = build / "AppIcon.ico"
    with Image.open(REPO / "packaging" / "AppIcon.icns") as image:
        image.save(icon, format="ICO", sizes=[(n, n) for n in (16, 24, 32, 48, 64, 128, 256)])
    command = [
        sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", "--windowed",
        "--onedir", "--name", APP, "--icon", str(icon), "--noupx",
        "--distpath", str(build / "dist"), "--workpath", str(build / "pyinstaller"),
        "--specpath", str(build), "--copy-metadata", "nd2wsi-viewer",
    ]
    for package in (
        "nd2wsi", "nd2", "zarr", "numcodecs", "dask", "tifffile", "imagecodecs",
        "limnd2", "ome_types", "xsdata", "xsdata_pydantic_basemodel", "webview",
        "pythonnet", "clr_loader",
    ):
        command += ["--collect-all", package]
    command += [str(REPO / "packaging" / "launch.py")]
    run(*command)
    bundle = build / "dist" / APP
    exe = bundle / f"{APP}.exe"
    if not exe.is_file():
        raise RuntimeError("PyInstaller did not create the Windows executable")
    manifest = {
        "app": APP,
        "version": version,
        "commit": provenance["base_commit"],
        "source": provenance,
        "python": platform.python_version(),
        "binary_architecture": "x64",
        "windows_arm64_mode": "Windows 11 x64 emulation",
        "web_renderer": "Microsoft Edge WebView2 Evergreen Runtime (system prerequisite)",
        "runtime_lock_sha256": sha256(REPO / "uv.lock"),
        "build_lock_sha256": sha256(REPO / "packaging" / "windows-build-requirements.txt"),
        "executable_sha256": sha256(exe),
        "packages": dict(sorted((d.metadata["Name"], d.version)
                                for d in importlib.metadata.distributions()
                                if d.metadata["Name"])),
    }
    (bundle / "build-info.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    shutil.copy2(REPO / "LICENSE", bundle / "LICENSE.txt")
    shutil.copy2(REPO / "packaging" / "WINDOWS-README.txt", bundle / "READ-ME.txt")
    # Include dependency licenses and metadata (useful on machines with no Python).
    licenses = bundle / "licenses"
    for distribution in importlib.metadata.distributions():
        for item in distribution.files or ():
            if ".dist-info/" not in str(item):
                continue
            if "license" in str(item).lower() or "copying" in str(item).lower():
                origin = Path(distribution.locate_file(item))
                if origin.is_file():
                    target = licenses / str(item)
                    target.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(origin, target)
    smoke(exe, source, out / "build-smoke")
    verify_source_files(provenance)
    archive = out / f"{APP}-{version}-windows-x64.zip"
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as target:
        for path in sorted(bundle.rglob("*")):
            if path.is_file():
                target.write(path, Path(APP) / path.relative_to(bundle))
    (out / f"{archive.name}.sha256").write_text(f"{sha256(archive)}  {archive.name}\n", encoding="ascii")
    print(f"Created {archive} ({archive.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
